services:
    api:
        container_name: api
        hostname: api
        build:
            context: .
            dockerfile: ./.devcontainer/Dockerfile
        working_dir: /app
        command: poetry run python -m uvicorn src.main:app --host '0.0.0.0' --port 8000 --log-level 'debug' --reload
        volumes:
        - .:/app
        ports:
        - 8000:8000
        networks:
        - api-network

volumes:
    home:

networks:
    api-network:
