version: '3'

services:
    api:
        container_name: api
        hostname: api
        build:
            context: ./docker/dev
        working_dir: /app
        command: python -m uvicorn src.main:app --host $API_HOST --port $API_PORT --reload
        tty: true
        env_file: .env
        environment:
        - PYTHONPATH=/app/src
        volumes:
        - .:/app:delegated
        - home:/home/$LOCAL_USER_NAME
        ports:
        - $API_PORT:$API_PORT
        networks:
        - api-network

volumes:
    home:

networks:
    api-network:
